name: deploy-on-self
on: 
  push:
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  main:
    runs-on: self-hosted
    steps:      
      - name: Move into right directory and execute update script
        run: |
          cd /home/joha_rasmus/botsProject;
          RUNNER_TRACKING_ID="";
          ./update.sh;
      
