name: ssh-and-deploy
on: [push, workflow_dispatch]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          echo "$GCP_SSH_KEY" > ssh.key
          chmod 600 ssh.key
        env:
          SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
      
      - name: SSH into server and execute deployment script
        run: ssh -i ssh.key joha_rasmus@"$GCP_IP" "cd botsProject && ./update.sh"
        env:
          GCP_IP: ${{ secrets.GCP_IP }}
      
