name: ssh-and-deploy
on: 
  push:
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: Set up SSH
        run: |
          echo "$GCP_SSH_KEY" > ssh.key
          chmod 600 ssh.key
        env:
          GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
      
      - name: SSH into server and execute deployment script
        run: cd botsProject && ./update.sh
        env:
          GCP_IP: ${{ secrets.GCP_IP }}
      
